
description: |
  General

step_size: 0.5                              # Max allowable distance that newly generated node can be from the nearest node in the tree                    
amount_of_runs: 1                           # Amount of runs executed 
debug_mode: true                            # True: Data isn't stored, as in debug modus
use_seed: true                              # True: Use a seed for the algorithm
seed:  1                                    # User defined seed
cprofiler: true                             # Use cprofiler to run the                     # Type of cost function: 'euclidean' (Max euclidean norm),  '-' (Chebyshev (= greatest diff in any dimension))
distance_metric: max                    # Type of dist function: 'euclidean' (Max euclidean norm),  '-' (Chebyshev (= greatest diff in any dimension))
cost_metric: euclidean
cost_reduction: max

shortcutting: true                          # Include Shortcutting after solution found
ptc_time : 300                              # Time for termination in sec


description: |
  Sampling strategy

p_goal: 0.9                                 # Probability of performing goal sampling
p_stay: 0.3                                 # Probability that robot stays in its pose (home pose) (if 1: isn't included)
general_goal_sampling: false                # True: For all tasks in mode goal sampling is done otherwise only for active task
mode_sampling: 1                         # Probability to choose new mode (0: uniformly, 1: greedy None: equally, else: manually set) 
informed_sampling: true                    # True: Informed sampling is applied 
informed_sampling_version: 0               # 0: mixture uniform and locally, 1: whole config, 2: = 1 but each agent separately 3: local 4: random local 5: by valentin 
p_uniform: 0.8                              #only used for version 3 in informed sampling version
gaussian: false

description: |
  Bi-RRT*

transition_nodes: 50                        # Number of generated transition nodes during mode initialization (only used in bi-rrt*)
birrtstar_version: 2                        # Version of Bi-RRT*: 1: Inspired by Bi-RRT* by b. Wang 2: Inspired by RRT-Connect by JJ. Kuffner/ RRT*-Connect by S.Klemm



description: |
  Q-RRT*

depth: 2                                    # User-defined depth parameter for the Quick-RRT* (0: Results in the same ouput as RRT*)


description: |
  dRRT*

batch_size: 400                            # Batch size for explicit grapths Gi to create implicit graph G
expand_iter: 10                            # Amount of iterations done in the expand funciton (grow the tree)

 








description: |
  TODO
# step-size adjustable based on dimension??
# adapt goal radius for more DOF -> make it dependent on DOF
# TODO's in planner.py and env.py
# Handle singularities properly!
# ATTENTION: The assumption is made that distance_metric and cost_type are the same for the batch_cost_torch function as it makes the algorithm more efficient -> would be easy changeable if necessary
